In [38]:
%load_ext autoreload
%autoreload 2 

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [39]:
# import the functions:

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

import functions
import re
import nltk
import joblib
import pandas as pd
from gensim.models import Word2Vec

#nltk.download('wordnet')
#nltk.download('punkt')

In [40]:
# Load the model
model = tf.keras.models.load_model('tf2_model')

In [41]:
# Load the tokenizer
tokenizer = joblib.load('saved_tokenizer.joblib')

In [42]:
# Load pre-trained Word2Vec model
word2vec_model = Word2Vec.load("word2vec.model")

In [43]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 500, 1000)         144008000 
                                                                 
 flatten_1 (Flatten)         (None, 500000)            0         
                                                                 
 dense_2 (Dense)             (None, 64)                32000064  
                                                                 
 dense_3 (Dense)             (None, 1)                 65        
                                                                 
Total params: 176008129 (671.42 MB)
Trainable params: 32000129 (122.07 MB)
Non-trainable params: 144008000 (549.35 MB)
_________________________________________________________________


In [44]:
tokenizer

In [45]:
tokenizer.texts_to_sequences("hello")

[[33224], [28324], [22641], [22641], [27210]]

In [50]:
def classify_message():
    # Get input from the user
    message = input("Enter the text you want to classify: ")
    
    # Preprocess the input message
    cleaned_message = functions.clean_text(message)
    print("Cleaned message:", cleaned_message)
    tokenized_message = functions.tokenizing_and_stopwords(cleaned_message)
    print("Tokenized message:", tokenized_message)
    lemmatized_message = functions.lemmatization_and_stopwords(tokenized_message)
    print("Lemmatized message:", lemmatized_message)
    
    # Convert text to sequence
    sequence = tokenizer.texts_to_sequences(lemmatized_message)
    print("Tokenized sequence:", sequence)
    
    # Pad sequence
    padded_sequence = pad_sequences(sequence, maxlen=500) 
    print("Padded sequence:", padded_sequence)
    
    # Make predictions using the loaded model
    prediction = model.predict(padded_sequence)
    print(prediction)
    
    if prediction[0] > 0.5:
        print("\n--- THIS IS BULLYING!!! --- This message is classified as bullying.")
    else:
        print("\n--- NO BULLYING. --- This message is not classified as bullying.")  
    
    return prediction[0]

In [51]:
prediction = classify_message()

# Thanks to all of you for the amazing time. We wish all of you 
# a glorious future from the bottom of ours hearts. <3 Love, Carmen & Juli

Enter the text you want to classify: you bitch
Cleaned message: you bitch
Tokenized message: bitch
Lemmatized message: bitch
Tokenized sequence: [[17154], [9754], [16234], [12887], [33224]]
Padded sequence: [[    0     0     0 ...     0     0 17154]
 [    0     0     0 ...     0     0  9754]
 [    0     0     0 ...     0     0 16234]
 [    0     0     0 ...     0     0 12887]
 [    0     0     0 ...     0     0 33224]]
1/1 [==============================] - 0s 45ms/step
[[8.3923078e-01]
 [6.7725894e-03]
 [8.4583871e-06]
 [6.5330166e-01]
 [3.4280559e-03]]

--- THIS IS BULLYING!!! --- This message is classified as bullying.


In [ ]:
########################################################################################################

In [11]:
# Load the second model
class_model = tf.keras.models.load_model('tf3_model')

In [12]:
# Load the tokenizer
class_tokenizer = joblib.load('class_tokenizer.joblib')

In [ ]:
# Load pre-trained Word2Vec model
#class_word2vec_model = Word2Vec.load("class_word2vec.model")

In [13]:
class_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 500, 500)          15803000  
                                                                 
 lstm (LSTM)                 (None, 100)               240400    
                                                                 
 dense (Dense)               (None, 64)                6464      
                                                                 
 dense_1 (Dense)             (None, 5)                 325       
                                                                 
Total params: 16050189 (61.23 MB)
Trainable params: 16050189 (61.23 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
class_tokenizer

In [18]:
###### testing with the classification type

def classify_message():
    # Get input from the user
    message = input("Enter the text you want to classify: ")
    
    # Preprocess the input message
    cleaned_message = functions.clean_text(message)
    print("Cleaned message:", cleaned_message)
    tokenized_message = functions.tokenizing_and_stopwords(cleaned_message)
    print("Tokenized message:", tokenized_message)
    lemmatized_message = functions.lemmatization_and_stopwords(tokenized_message)
    print("Lemmatized message:", lemmatized_message)
    
    # Convert text to sequence
    sequence = tokenizer.texts_to_sequences(lemmatized_message)
    #print("Tokenized sequence:", sequence)
    
    # Pad sequence
    padded_sequence = pad_sequences(sequence, maxlen=500) 
    #print("Padded sequence:", padded_sequence)
    
    # Make predictions using the loaded model
    prediction = model.predict(padded_sequence)
    print(prediction)
      
    if prediction[0] > 0.5:
        print("\n--- THIS IS BULLYING!!! --- This message is classified as bullying.")
        
        # Use the second model to classify the type of bullying
        class_sequence = class_tokenizer.texts_to_sequences(lemmatized_message)
        class_padded_sequence = pad_sequences(class_sequence, maxlen=500) 
        class_prediction = class_model.predict(class_padded_sequence)
        print("\nType of Bullying:", class_prediction)

    else:
        print("\n--- NO BULLYING. --- This message is not classified as bullying.")  
    
    return class_prediction[0]

In [19]:
class_prediction = classify_message()

Enter the text you want to classify: you bitch
Cleaned message: you bitch
Tokenized message: bitch
Lemmatized message: bitch
1/1 [==============================] - 0s 423ms/step
[[8.3923078e-01]
 [6.7725894e-03]
 [8.4583871e-06]
 [6.5330166e-01]
 [3.4280559e-03]]

--- THIS IS BULLYING!!! --- This message is classified as bullying.
1/1 [==============================] - 0s 190ms/step

Type of Bullying: [[1.0000000e+00 1.0671426e-09 2.9529843e-09 2.6727087e-09 8.3026752e-10]
 [1.0000000e+00 1.0671426e-09 2.9529843e-09 2.6727087e-09 8.3026752e-10]
 [1.0000000e+00 1.0671426e-09 2.9529843e-09 2.6727087e-09 8.3026752e-10]
 [1.0000000e+00 1.0671426e-09 2.9529843e-09 2.6727087e-09 8.3026752e-10]
 [1.0000000e+00 1.0671426e-09 2.9529843e-09 2.6727087e-09 8.3026752e-10]]
